#!/bin/bash/

echo "$(tput setaf 3)Please wait while the script is configured" && sleep 1

sudo mv shutdown-listener.py /usr/local/bin/
sudo chmod +x /usr/local/bin/shutdown-listener.py

sudo mv shutdown-listener.sh /etc/init.d/
sudo chmod +x /etc/init.d/shutdown-listener.sh
sudo update-rc.d shutdown-listener.sh defaults

echo "Done installing!" && sleep 1

sudo rm install

exit 0

