#!/bin/bash/

echo "$(tput setaf 4)Please wait while the script is configured" && sleep 3
echo -ne '#                         (0%)\r' sleep 1

sudo mv shutdown-listener.py /usr/local/bin/
sudo chmod +x /usr/local/bin/shutdown-listener.py
echo -ne '#####                     (30%)\r'

sudo mv shutdown-listener.sh /etc/init.d/
sudo chmod +x /etc/init.d/shutdown-listener.sh
sudo update-rc.d shutdown-listener.sh defaults
echo -ne '##########################(49%)\r' && sleep 1

echo "Done installing!" && sleep 1
echo "Starting Initial Service" && sleep 1
echo -ne '##########################(74%)\r' && sleep 1

echo -ne '##########################(99%)\r'

sudo rm Setup
echo -ne '\n'

exit 0

