#!/bin/bash/

echo "$(tput setaf 6)Please wait while the script is configured"

sudo mv shutdown-listener.py /usr/local/bin/
sudo chmod +x /usr/local/bin/shutdown-listener.py
sudo mv shutdown-listener.sh /etc/init.d/
sudo chmod +x /etc/init.d/shutdown-listener.sh
sudo update-rc.d shutdown-listener.sh defaults
sudo rm install README.md
sudo /etc/init.d/shutdown-listener.sh start

echo "Your install is complete." && sleep 1
exit 0

