#!/bin/bash

echo "This script is the test script to organize the newly loaded files." && sleep 5
echo "Running"

touch TestDir
sudo mv shutdown-listener.py /home/BashPink/TestDir

echo "Done"

exit 0
